version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /media
  static_dir: eucaby/media

- url: /static
  static_dir: eucaby/static
  expiration: 0

- url: /tasks/.*
  script: eucaby.wsgi.application
  login: admin

- url: /.*
  script: eucaby.wsgi.application

env_variables:
  DJANGO_SETTINGS_MODULE: 'eucaby.eucaby.settings'

libraries:
- name: django
  version: 1.5

- name: MySQLdb
  version: latest

- name: ssl
  version: latest

builtins:
- django_wsgi: on

#inbound_services:
#- warmup

skip_files:
- ^\.git
- ^\.idea
- ^(.*/)?index\.yaml
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^deploy*
- ^lib/Django.*
- ^lib/django
- ^lib/MySQL
- ^lib/_mysql
- ^lib/PyYAML*
- ^lib/yaml
- ^eucaby_rt
- ^eucaby_mobile
