runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /media
  static_dir: eucaby/media
  secure: always

- url: /static
  static_dir: eucaby/static
  secure: always
  expiration: 0

- url: .*
  script: eucaby.eucaby.wsgi.app
  secure: always

libraries:
- name: MySQLdb
  version: latest

- name: ssl
  version: latest

builtins:
- django_wsgi: on

#inbound_services:
#- warmup

includes:
- common.yaml
