application: auto
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /media
  static_dir: media

- url: /static
  static_dir: static
  expiration: 0

#- url: /remoteapi.*
#  script: google.appengine.ext.remote_api.handler.application
#  login: admin

- url: /_ah/spi/.*
  script: eucaby.api.eucaby_api.application

- url: /tasks/.*
  script: eucaby.wsgi.application
  login: admin

- url: .*
  script: eucaby.wsgi.application

env_variables:
  DJANGO_SETTINGS_MODULE: 'eucaby.eucaby.settings'

libraries:
- name: django
  version: 1.5

- name: endpoints
  version: 1.0

- name: MySQLdb
  version: latest

- name: ssl
  version: latest

builtins:
- django_wsgi: on
#- remote_api: on

skip_files:
- ^\.git
- ^\.idea
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^lib/Django.*
- ^lib/django
- ^lib/MySQL
- ^lib/_mysql
- ^lib/PyYAML*
- ^lib/yaml
- ^prototype

