runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /media
  static_dir: eucaby/media

- url: /static
  static_dir: eucaby/static
  expiration: 0

- url: .*
  script: eucaby.eucaby.wsgi.app

libraries:
- name: MySQLdb
  version: latest
- name: ssl
  version: latest

#env_variables:
#  DJANGO_SETTINGS_MODULE: 'eucaby.eucaby.settings'

builtins:
- django_wsgi: on

#inbound_services:
#- warmup

includes:
- common.yaml
